### ISSUE TITLE
Update node `engines` versions

### ISSUE THREAD

**Issue by adamsoderstrom** [noaignite/accelerator#154]
To atleast `v20` (`>=20`) to match the `.nvmrc` file (#156).

**Comment by adamsoderstrom** [comment]
We should probably be careful to not specify `>= *node-version*` in our `package.json`'s, so we don't accidentally run / build the packages with a incompatible Node version.

**Comment by adamsoderstrom** [comment]
Since EOL has passed for Node v14, we don't have to consider that in older projects. If an older project would have to use a new package constrained to a newer Node version, then that project would need to update Node version.

**Comment by maeertin** [comment]
The monorepo roots `engines` node version has been updated to `>=20` to match the version set in `.nvmrc`.

Updating each individual package node version should also be done but perhaps retroactively as we work with the each package as this would mean a breaking change? But we should definitively update them as we're no longer testing the packages for those older node versions.
