### ISSUE TITLE
[docs] Add deployment of docs

### ISSUE THREAD

**Issue by maeertin** [noaignite/accelerator#30]

**Comment by alexanderflink** [comment]
Which docs do you mean here? The storybook docs?

**Comment by maeertin** [comment]
Yes exactly @alexanderflink, the Storybook docs found in the root of the repo. Would be nice to be able to host this somewhere.

Another discussion would be if we should use something else besides Storybook for the docs to enable all packages in the mono-repo to have their section in the root docs :)
