### ISSUE TITLE
[docs] Create root level docs for all packages

### ISSUE THREAD

**Issue by alexanderflink** [noaignite/accelerator#52]
It would be nice to have all documentation collected in one place in the root of the repo. We could also deploy them on the same site, with links for both storybook docs and generated typescript docs.

**Comment by alexanderflink** [comment]
Suggestion: Create a static next.js app where pages are built using markdown files. We should make sure the markdown files can include React components so we can show examples.

**Comment by maeertin** [comment]
I now have a working example of this with tailwind css configured for use :)
