### ISSUE TITLE
Feature parity with @oakwood/accelerator package

### ISSUE THREAD

**Issue by alexanderflink** [noaignite/accelerator#56]
We need to have feature parity with the most used features of the old @oakwood/accelerator package. Some features may move into separate packages and change name, but the functionality of @oakwood/accelerator should be available within the @noaignite/accelerator packages.

Currently available features:

- [x] Centra Checkout API client
- [x] Centra React context
- [x] Centra PaymentForm react component (changed to PaymentEmbed)
- [ ] <s>Wordpress API client</s>
- [ ] <s>Wordpress utility functions for rendering blocks from page (getInitialProps, getPage etc)</s>
- [ ] MetaData react component

**Comment by alexanderflink** [comment]
MetaData could start out it's life in create-ignite-app

**Comment by adamsoderstrom** [comment]
New projects wouldn't benefit of a `MetaData` component, since the App router uses `generateMetadata` function ([see](https://nextjs.org/docs/app/api-reference/functions/generate-metadata)).

Closing.
