### ISSUE TITLE
[core] @babel/plugin-transform-runtime @babel/runtime packages needed?

### ISSUE THREAD

**Issue by maeertin** [noaignite/accelerator#66]
As I understand it, these packages help avoid babel helper duplication and thus could improve performance. Research if these packages are beneficial and if so make sure accelerator packages are bundled with `@babel/runtime`. Alternatively, remove if not needed.

https://babeljs.io/docs/en/babel-plugin-transform-runtime
https://babeljs.io/docs/en/babel-runtime

**Comment by alexanderflink** [comment]
We should check if our transpiled code actually uses any of the babel helpers (since we are transpiling to quite modern js), if not I think these could be removed.

**Comment by adamsoderstrom** [comment]
Closing, because no longer relevant
