### ISSUE TITLE
[react-centra-checkout] Add automated tests

### ISSUE THREAD

**Issue by maeertin** [noaignite/accelerator#67]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/557486/182872533-b824804c-fa9e-4d61-8f00-19056a571375.png">

Typescript files have been added to test coverage and now show up when running `yarn test:coverage` (or `yarn test` for all tests).

**Comment by adamsoderstrom** [comment]
@alexanderflink Can you submit your branch as a drafted PR?

**Comment by alexanderflink** [comment]
#179 Done!
