### ISSUE TITLE
[oui/Media] Update component with native lazy loading

### ISSUE THREAD

**Issue by maeertin** [noaignite/accelerator#75]
Media component should be updated to take advantage of now well supported native lazy loading capabilities. Question is if intersection observer solution should be kept for videos.

**Comment by alexanderflink** [comment]
This should be released as a breaking change together with #76

**Comment by maeertin** [comment]
This has been added as of version 4.0.0.
https://github.com/noaignite/accelerator/blob/main/packages/oui/CHANGELOG.md#400-2023-01-27
