### ISSUE TITLE
[oui/AspectRatio] Deprecate component

### ISSUE THREAD

**Issue by maeertin** [noaignite/accelerator#76]
Deprecate the OuiAspectRatio component as we now have aspect-ratio css support in latest 2 major browsers.

**Comment by alexanderflink** [comment]
This should be released as a breaking change together with #75

**Comment by maeertin** [comment]
AspectRatio is now removed as of version 4.0.0.
https://github.com/noaignite/accelerator/blob/main/packages/oui/CHANGELOG.md#400-2023-01-27
