### ISSUE TITLE
Create package for centra mock data

### ISSUE THREAD

**Issue by alexanderflink** [noaignite/accelerator#77]
Suggested name @noaignite/centra-mock-data

Suggestions on imports:

```
import { products, selection } from '@noaignite/centra-mock-data'
```

**Comment by maeertin** [comment]
suggestion: Perhaps even @noaignite/centra-mocks as the package name? Less to write ;) Additionally, we might include utils / generator functions for the mocks (not just data).

**Comment by maeertin** [comment]
Initial package now created.
